### ISSUE TITLE
GreetingsFromYoutube

### ISSUE THREAD

**Issue by Doomyslayer** [jade-bejide/SimpleCalculator#1]
Hi there! I'm OperonFun from Youtube hahaha. I was looking a mean to contact you, because I discovered a couple things about your calculator code:

1. Dividing per 0 does nothing in the GUI, but my Visual Studio Code terminal gives an error, so a good improvement would be to display a message of "syntax error" or something like that (that's what real calculator show when you do anything/0)

2. Although you can get negatives as results (like i.e.: "3-4" will give a "-1"), then you can't keep operating with that number. For example, I did "5-8", that gave me a "-3.0", then I tried "-3.0+7", and this error popped up in my terminal:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python37\lib\site-packages\guizero\PushButton.py", line 206, in _command_callback
    self._command()
  File "c:\Users\usuario\Documents\PROGRAMACION\DooCalcs3500\v1_3_5\britcalc", line 66, in calculate
    display.value = getOperator(hold[0], hold[1], hold[2])
  File "c:\Users\usuario\Documents\PROGRAMACION\DooCalcs3500\v1_3_5\britcalc", line 30, in getOperator
    answer = float(num1) - float(num2)
ValueError: could not convert string to float:

I'm thinking about a way of fixing it, and adding the "," operator so you can enter decimal numbers like "8,066", "5,3", etc. If I come up with something, I'll post it here.

Well, that's all. This example code really got me into programming with guizero hahaha, I'm adding a lot of stuff to it.

Anyway, till next time!
Doomy.

**Comment by jade-bejide** [comment]
Hi Doomy, 

If you fork this repository and make a pull request, I'll merge the changes where appropriate. Thanks for your contribution :)
